# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
 secret_key_base: 3453c963810fa6892c37d1827d783f770687f041759fce61dbc599847f4f4dd48e6904f69d8d8e9b2a021a8b472e1f0994980f979a672aba2a5ce7fee7fe51e8

test:
 secret_key_base: c49b5e0f20aa447fad36c4a047f0849dbadb669a0ea8cb856cf2e4db152a54f1d1d158080e8408fbfa2d11c676ddedc335513ba6ce12c6685f94f5083dedff69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>